//
//  StoriesView.swift
//  VoicesAI
//
//  Created by Hidayat Abisena on 24/04/24.
//

import SwiftUI

struct StoriesView: View {
    @StateObject private var storyVM = StoryVM()
    @StateObject private var speechVM = SpeechVM()
    
    @State private var selectedTopic: Topics = .persahabatan
    @State private var selectedMood: Mood = .bahagia
    
   // @State private var todayStory: String = ""
    
    var body: some View {
        NavigationStack {
            Form {
                // MARK: - PICKER VIEW
                Section {
                    Picker("Choose topics", selection: $selectedTopic) {
                        ForEach(Topics.allCases) { topic in
                            Text(topic.rawValue).tag(topic)
                        }
                    }
                    
                    Picker("Choose Mood", selection: $selectedMood) {
                        ForEach(Mood.allCases) { mood in
                            Text(mood.rawValue).tag(mood)
                        }
                    }
                } header: {
                    Text("Topics")
                } footer: {
                    Text("Choose any topics and mood")
                }
                
                // MARK: - TEXT EDITOR
                Section {
                    TextEditor(text: $storyVM.displayedStoryText)
                        .frame(height: 200)
                        .font(.system(.headline, design: .rounded))
                        .foregroundStyle(.blue)
                        .disabled(storyVM.isLoading)
                        .overlay {
                            storyVM.isLoading ? ProgressView() : nil
                        }
                } header: {
                    Text("Todays Story")
                } footer: {
                    Text("This stories are being generated by Gemini AI.")
                }
                
                // MARK: - GENERATE STORY
                Button {
                    todaysStory()
                } label: {
                    if storyVM.isLoading {
                        ProgressView().scaleEffect(1)
                    } else {
                        Text(storyVM.storyText.isEmpty ? "Generate".uppercased() : "Speech".uppercased())
                            .font(.system(.callout, design: .rounded))
                            .fontWeight(.bold)
                    }
                    
                }
                .buttonStyle(.plain)
                .frame(minWidth: 0, maxWidth: .infinity)
                
            }
            .navigationTitle("Stories")
            .tint(.primary)
        }
    }
}

#Preview {
    StoriesView()
}

// MARK: - PLAY SPEECH
extension StoriesView {
    func playSpeech() {
        let apiKey = UserDefaults.standard.string(forKey: "ElevenLabsAPIKey") ?? ""
        
        Task {
            await speechVM.generateAndPlaySpeech(from:storyVM.displayedStoryText, apiKey: apiKey)
        }
    }
    
    func generateStory() {
        Task {
            await storyVM.generateStory(topic: selectedTopic, mood: selectedMood)
        }
    }
    
    private func todaysStory() {
        if storyVM.displayedStoryText.isEmpty {
            generateStory()
        } else {
            playSpeech()
        }
    }
}
